#!/bin/bash

#
#  plot
#
#  Copyright 2012 Miguel Sánchez de León Peque <msdeleonpeque@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#


mkdir -p build

# Print slice LUTs utilization
./print_graphs \
	X=N_PORTS \
	XL="Number of ports (N)" \
	Y=SLICE_LUTS \
	YL="LUTs used" \
	D=CSPLINE,POINTS \
	F=TARGET_DEVICE,DESIGN_GOAL,DESIGN_STRATEGY,GLOBAL_OPTIMIZATION,BROADCAST_ENABLED

# Print BRAM utilization
./print_graphs \
	X=N_PORTS \
	XL="Number of ports (N)" \
	Y=BLOCK_RAM \
	YL="BRAMs used" \
	D=CSPLINE,POINTS \
	F=TARGET_DEVICE,DESIGN_GOAL,DESIGN_STRATEGY,GLOBAL_OPTIMIZATION,BROADCAST_ENABLED

# Print MIATBC comparison for BROADCAST_ENABLED
./print_graphs \
	X=N_PORTS \
	XL="Number of ports (N)" \
	Y=MIATBC \
	YL="Delay (ns)" \
	D=BEZIER,POINTS \
	C=BROADCAST_ENABLED \
	F=TARGET_DEVICE,DESIGN_GOAL,DESIGN_STRATEGY,GLOBAL_OPTIMIZATION

# Print MORTAC comparison for BROADCAST_ENABLED
./print_graphs \
	X=N_PORTS \
	XL="Number of ports (N)" \
	Y=MORTAC \
	YL="Delay (ns)" \
	D=BEZIER,POINTS \
	C=BROADCAST_ENABLED \
	F=TARGET_DEVICE,DESIGN_GOAL,DESIGN_STRATEGY,GLOBAL_OPTIMIZATION

# Print SLICE_LUTS comparison for BROADCAST_ENABLED
./print_graphs \
	X=N_PORTS \
	XL="Number of ports (N)" \
	Y=SLICE_LUTS \
	YL="LUTs used" \
	D=CSPLINE,POINTS \
	C=BROADCAST_ENABLED \
	F=TARGET_DEVICE,DESIGN_GOAL,DESIGN_STRATEGY,GLOBAL_OPTIMIZATION

# Print MIATBC and MORTAC
./print_graphs \
	X=N_PORTS \
	XL="Number of ports (N)" \
	Y=MIATBC,MORTAC \
	YL="Delay (ns)" \
	D=BEZIER,POINTS \
	F=TARGET_DEVICE,DESIGN_GOAL,DESIGN_STRATEGY,GLOBAL_OPTIMIZATION,BROADCAST_ENABLED

# Print MIATBC and MORTAC comparison for BROADCAST_ENABLED
./print_graphs \
	X=N_PORTS \
	XL="Number of ports (N)" \
	Y=MIATBC,MORTAC \
	YL="Delay (ns)" \
	D=BEZIER,POINTS \
	C=BROADCAST_ENABLED \
	F=TARGET_DEVICE,DESIGN_GOAL,DESIGN_STRATEGY,GLOBAL_OPTIMIZATION

# Print MIATBC_LOGIC and MIATBC_ROUTE
./print_graphs \
	X=N_PORTS \
	XL="Number of ports (N)" \
	Y=MIATBC_LOGIC,MIATBC_ROUTE \
	YL="Delay (ns)" \
	D=BEZIER,POINTS \
	F=TARGET_DEVICE,DESIGN_GOAL,DESIGN_STRATEGY,GLOBAL_OPTIMIZATION,BROADCAST_ENABLED

# Print MORTAC_LOGIC and MORTAC_ROUTE
./print_graphs \
	X=N_PORTS \
	XL="Number of ports (N)" \
	Y=MORTAC_LOGIC,MORTAC_ROUTE \
	YL="Delay (ns)" \
	D=BEZIER,POINTS \
	F=TARGET_DEVICE,DESIGN_GOAL,DESIGN_STRATEGY,GLOBAL_OPTIMIZATION,BROADCAST_ENABLED

# Print MIATBC_LOGIC and MIATBC_ROUTE comparison for BROADCAST_ENABLED
./print_graphs \
	X=N_PORTS \
	XL="Number of ports (N)" \
	Y=MIATBC_LOGIC,MIATBC_ROUTE \
	YL="Delay (ns)" \
	D=BEZIER,POINTS \
	C=BROADCAST_ENABLED \
	F=TARGET_DEVICE,DESIGN_GOAL,DESIGN_STRATEGY,GLOBAL_OPTIMIZATION

# Print MORTAC_LOGIC and MORTAC_ROUTE comparison for BROADCAST_ENABLED
./print_graphs \
	X=N_PORTS \
	XL="Number of ports (N)" \
	Y=MORTAC_LOGIC,MORTAC_ROUTE \
	YL="Delay (ns)" \
	D=BEZIER,POINTS \
	C=BROADCAST_ENABLED \
	F=TARGET_DEVICE,DESIGN_GOAL,DESIGN_STRATEGY,GLOBAL_OPTIMIZATION
